const diwaliLightProducts = [
  {id:"KE-DL-001",category:"diwali-lights",name:"15 MTR LED String Light",images:["assets/images/diwali-lights/KE-DL-001.jpg"],specs:{}},
  {id:"KE-DL-002",category:"diwali-lights",name:"20 MTR LED String Light",images:["assets/images/diwali-lights/KE-DL-002.jpg"],specs:{}},
  {id:"KE-DL-003",category:"diwali-lights",name:"10 MTR Green LED String Light",images:["assets/images/diwali-lights/KE-DL-003.jpg"],specs:{}},
  {id:"KE-DL-004",category:"diwali-lights",name:"30 MTR Multi-Color LED String Light",images:["assets/images/diwali-lights/KE-DL-004.jpg"],specs:{}},
  {id:"KE-DL-005",category:"diwali-lights",name:"40 MTR Milky Ball String Light",images:["assets/images/diwali-lights/KE-DL-005.jpg"],specs:{}},
  {id:"KE-DL-006",category:"diwali-lights",name:"50 MTR Warm White String Light",images:["assets/images/diwali-lights/KE-DL-006.jpg"],specs:{}},
  {id:"KE-DL-007",category:"diwali-lights",name:"60 MTR Red LED String Light",images:["assets/images/diwali-lights/KE-DL-007.jpg"],specs:{}},
  {id:"KE-DL-008",category:"diwali-lights",name:"Tiranga Jhalar",images:["assets/images/diwali-lights/KE-DL-008.jpg"],specs:{}},
  {id:"KE-DL-009",category:"diwali-lights",name:"Crystal Gel Droplet",images:["assets/images/diwali-lights/KE-DL-009.jpg"],specs:{}},
  {id:"KE-DL-010",category:"diwali-lights",name:"Snow Flakes",images:["assets/images/diwali-lights/KE-DL-010.jpg"],specs:{}},
  {id:"KE-DL-011",category:"diwali-lights",name:"Milky Ball",images:["assets/images/diwali-lights/KE-DL-011.jpg"],specs:{}},
  {id:"KE-DL-012",category:"diwali-lights",name:"Crackle Ball",images:["assets/images/diwali-lights/KE-DL-012.jpg"],specs:{}},
  {id:"KE-DL-013",category:"diwali-lights",name:"Silicone Flower LED",images:["assets/images/diwali-lights/KE-DL-013.jpg"],specs:{}},
  {id:"KE-DL-014",category:"diwali-lights",name:"Star WW",images:["assets/images/diwali-lights/KE-DL-014.jpg"],specs:{}},
  {id:"KE-DL-015",category:"diwali-lights",name:"Pan Ganesha",images:["assets/images/diwali-lights/KE-DL-015.jpg"],specs:{}},
  {id:"KE-DL-016",category:"diwali-lights",name:"Metal Leaf",images:["assets/images/diwali-lights/KE-DL-016.jpg"],specs:{}},
  {id:"KE-DL-017",category:"diwali-lights",name:"Crystal Gell Ball",images:["assets/images/diwali-lights/KE-DL-017.jpg"],specs:{}},
  {id:"KE-DL-018",category:"diwali-lights",name:"Crackle Ball",images:["assets/images/diwali-lights/KE-DL-018.jpg"],specs:{}},
  {id:"KE-DL-019",category:"diwali-lights",name:"Star Smiley",images:["assets/images/diwali-lights/KE-DL-019.jpg"],specs:{}},
  {id:"KE-DL-020",category:"diwali-lights",name:"Crystal Gel Droplet Clear",images:["assets/images/diwali-lights/KE-DL-020.jpg"],specs:{}},
  {id:"KE-DL-021",category:"diwali-lights",name:"Crackle Heart",images:["assets/images/diwali-lights/KE-DL-021.jpg"],specs:{}},
  {id:"KE-DL-022",category:"diwali-lights",name:"Crystal Gel WW",images:["assets/images/diwali-lights/KE-DL-022.jpg"],specs:{}},
  {id:"KE-DL-023",category:"diwali-lights",name:"Diya 6+6",images:["assets/images/diwali-lights/KE-DL-023.jpg"],specs:{}},
  {id:"KE-DL-024",category:"diwali-lights",name:"USB String Light",images:["assets/images/diwali-lights/KE-DL-024.jpg"],specs:{}},
  {id:"KE-DL-025",category:"diwali-lights",name:"Eid Star 5+5",images:["assets/images/diwali-lights/KE-DL-025.jpg"],specs:{}},
  {id:"KE-DL-026",category:"diwali-lights",name:"RGB Eid Light",images:["assets/images/diwali-lights/KE-DL-026.jpg"],specs:{}},
  {id:"KE-DL-027",category:"diwali-lights",name:"Bonsai Tree",images:["assets/images/diwali-lights/KE-DL-027.jpg"],specs:{}},
  {id:"KE-DL-028",category:"diwali-lights",name:"Ring Light Eid",images:["assets/images/diwali-lights/KE-DL-028.jpg"],specs:{}},
  {id:"KE-DL-029",category:"diwali-lights",name:"Heart 6+6",images:["assets/images/diwali-lights/KE-DL-029.jpg"],specs:{}},
  {id:"KE-DL-030",category:"diwali-lights",name:"Cotton Ball",images:["assets/images/diwali-lights/KE-DL-030.jpg"],specs:{}},
  {id:"KE-DL-031",category:"diwali-lights",name:"Rose LED",images:["assets/images/diwali-lights/KE-DL-031.jpg"],specs:{}},
  {id:"KE-DL-032",category:"diwali-lights",name:"Ring Light 6+6",images:["assets/images/diwali-lights/KE-DL-032.jpg"],specs:{}},
  {id:"KE-DL-033",category:"diwali-lights",name:"Deer Star Curtain 6+6",images:["assets/images/diwali-lights/KE-DL-033.jpg"],specs:{}},
  {id:"KE-DL-034",category:"diwali-lights",name:"Tree Bottle",images:["assets/images/diwali-lights/KE-DL-034.jpg"],specs:{}},
  {id:"KE-DL-035",category:"diwali-lights",name:"Bottle LED",images:["assets/images/diwali-lights/KE-DL-035.jpg"],specs:{}},
  {id:"KE-DL-036",category:"diwali-lights",name:"Crackle Ball",images:["assets/images/diwali-lights/KE-DL-036.jpg"],specs:{}},
  {id:"KE-DL-037",category:"diwali-lights",name:"Diya 14 LED",images:["assets/images/diwali-lights/KE-DL-037.jpg"],specs:{}},
  {id:"KE-DL-038",category:"diwali-lights",name:"Wall Hanging Star",images:["assets/images/diwali-lights/KE-DL-038.jpg"],specs:{}},
  {id:"KE-DL-039",category:"diwali-lights",name:"Honey Bee",images:["assets/images/diwali-lights/KE-DL-039.jpg"],specs:{}},
  {id:"KE-DL-040",category:"diwali-lights",name:"Cork LED",images:["assets/images/diwali-lights/KE-DL-040.jpg"],specs:{}},
  {id:"KE-DL-041",category:"diwali-lights",name:"Christmas Bottle",images:["assets/images/diwali-lights/KE-DL-041.jpg"],specs:{}},
  {id:"KE-DL-042",category:"diwali-lights",name:"Snowflakes 6+6",images:["assets/images/diwali-lights/KE-DL-042.jpg"],specs:{}},
  {id:"KE-DL-043",category:"diwali-lights",name:"Christmas Toy",images:["assets/images/diwali-lights/KE-DL-043.jpg"],specs:{}},
  {id:"KE-DL-044",category:"diwali-lights",name:"Wish Ball 6+6",images:["assets/images/diwali-lights/KE-DL-044.jpg"],specs:{}},
  {id:"KE-DL-045",category:"diwali-lights",name:"Multi Snowflakes",images:["assets/images/diwali-lights/KE-DL-045.jpg"],specs:{}},
  {id:"KE-DL-046",category:"diwali-lights",name:"Multi Wish Ball 6+6",images:["assets/images/diwali-lights/KE-DL-046.jpg"],specs:{}},
  {id:"KE-DL-047",category:"diwali-lights",name:"Silicone Flower LED",images:["assets/images/diwali-lights/KE-DL-047.jpg"],specs:{}},
  {id:"KE-DL-048",category:"diwali-lights",name:"14 LED Bulb",images:["assets/images/diwali-lights/KE-DL-048.jpg"],specs:{}},
  {id:"KE-DL-049",category:"diwali-lights",name:"Lemon LED",images:["assets/images/diwali-lights/KE-DL-049.jpg"],specs:{}},
  {id:"KE-DL-050",category:"diwali-lights",name:"Diya 6+6 Curtain",images:["assets/images/diwali-lights/KE-DL-050.jpg"],specs:{}},
  {id:"KE-DL-051",category:"diwali-lights",name:"Silicone Flower LED",images:["assets/images/diwali-lights/KE-DL-051.jpg"],specs:{}},
  {id:"KE-DL-052",category:"diwali-lights",name:"Diya 6+6 Decorative Curtain",images:["assets/images/diwali-lights/KE-DL-052.jpg"],specs:{}},
  {id:"KE-DL-053",category:"diwali-lights",name:"Clip 10 LED",images:["assets/images/diwali-lights/KE-DL-053.jpg"],specs:{}},
  {id:"KE-DL-054",category:"diwali-lights",name:"Star 6+6",images:["assets/images/diwali-lights/KE-DL-054.jpg"],specs:{}},
  {id:"KE-DL-055",category:"diwali-lights",name:"Leaf Curtain",images:["assets/images/diwali-lights/KE-DL-055.jpg"],specs:{}},
  {id:"KE-DL-056",category:"diwali-lights",name:"Small Snowflakes",images:["assets/images/diwali-lights/KE-DL-056.jpg"],specs:{}},
  {id:"KE-DL-057",category:"diwali-lights",name:"Solar Firefly Light",images:["assets/images/diwali-lights/KE-DL-057.jpg"],specs:{}},
  {id:"KE-DL-058",category:"diwali-lights",name:"Star LED",images:["assets/images/diwali-lights/KE-DL-058.jpg"],specs:{}},
  {id:"KE-DL-059",category:"diwali-lights",name:"Foam Lotus Diya",images:["assets/images/diwali-lights/KE-DL-059.jpg"],specs:{}},
  {id:"KE-DL-060",category:"diwali-lights",name:"Wooden Toy LED",images:["assets/images/diwali-lights/KE-DL-060.jpg"],specs:{}},
  {id:"KE-DL-061",category:"diwali-lights",name:"Wooden Star LED",images:["assets/images/diwali-lights/KE-DL-061.jpg"],specs:{}},
  {id:"KE-DL-062",category:"diwali-lights",name:"Wooden Heart Light",images:["assets/images/diwali-lights/KE-DL-062.jpg"],specs:{}},
  {id:"KE-DL-063",category:"diwali-lights",name:"Pineapple LED",images:["assets/images/diwali-lights/KE-DL-063.jpg"],specs:{}},
  {id:"KE-DL-064",category:"diwali-lights",name:"Silicone Rose LED",images:["assets/images/diwali-lights/KE-DL-064.jpg"],specs:{}}
];

products.push(...diwaliLightProducts);